<form action="<?php echo $this->baseUrl ?>/index/<?php
      echo $this->action; ?>" method="post">
   <div>
      <!--<label for="author">Autor</label> -->
      <input type="hidden" name="author" value="Gość"/>
   </div><br/>
    <br/>
   <div>
      <label for="cathegory">Kategoria</label>
      <input required="required" type="text" name="cathegory" placeholder="Naciśnij dwa razy" list="datalist"/>
      <datalist id="datalist">
          <option value="problem z komputerem w sali">
          <option value="awaria komputera pracownika">
          <option value="inne">
          <option value="awaria sieci">
      </datalist>
   </div><br/>
   
   <div>
      <label for="problem_describe">Opis problemu</label>
      <input required="required" rows="4" cols="8" type="text" name="problem_describe" value="<?php
         echo $this->escape($this->problem_describe);?>"/>
   </div>
    
   <div>
      <!--<label for="send_data">Data wysłania</label>-->
      <input type="hidden" name="send_data" value="<?php
         echo date("Y-m-d");?>"/>
   </div>
    
   <div>
      <!--<label for="end_data">Data zakończenia</label>-->
      <input type="hidden" name="end_data" value="0"/>
   </div>
    
   <div>
      <!--<label for="status">Status</label>-->
      <input type="hidden" name="status" value="oczekujący"/>
   </div>
    
   <div>
      <!--<label for="ip_number">Numer IP</label>-->
      <input type="hidden" name="ip_number" value="<?php
         echo $_SERVER['REMOTE_ADDR'];?>"/>
   </div><br/>     
   
   <div>
      <label hidden for="admin1">Admin 1</label>
      <input type="hidden" name="admin1" value="-"/>
   </div><br/>  
   
   <div>
      <label hidden for="admin2">Admin 2</label>
      <input type="hidden" name="admin2" value="-"/>
   </div><br/>  
   
   <div>
       <label hidden for="admin3">Admin 3</label>
      <input type="hidden" name="admin3" value="-"/>
   </div><br/>
    
    
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->guestticket->id; ?>" /> 
      <input type="submit" name="add" value="Dodaj" />
   </div>
</form>