<?php echo $this->render('header.phtml'); ?>

  <h1><?=$this->escape($this->wellcome);?></h1>
  
  <h3>Użytkownik niezalogowany może TUTAJ wysłać ticket.</h3>
  
  <h3> Aby wysłać ticket ze swojego konta musisz się zalogować.</h3>
  
  <p><a href="<?php echo $this->baseUrl; ?>/index/add">Dodaj Ticket</a></p>
  
  <p>Jeżeli nie możesz wysłać ticketu z tej strony, to możesz to zrobić wysyłając e-maila
  na adres awariauwm@o2.pl. W temacie wpisz nazwę kategorii, np. awaria komputera, awaria sieci, inne,
  a w treści wiadomości opisz problem.
  </p>
  
<?php echo $this->render('footer.phtml'); ?>