<form action="<?php echo $this->baseUrl ?>/index/<?php
      echo $this->action; ?>" method="post">
   <div>
      <label for="artist">Artist</label> 
      <input type="text" name="artist" value="<?php
         echo $this->escape(trim($this->album->artist));?>"/>
   </div>
   <div>
      <label for="title">Title</label>
      <input type="text" name="title" value="<?php
         echo $this->escape($this->album->title);?>"/>
   </div>
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->album->id; ?>" /> 
      <input type="submit" name="add" value="<?php
         echo $this->escape($this->buttonText); ?>" />
   </div>
</form>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
   <head>
      <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
      <title><?php echo $this->escape($this->title); ?></title>
         <link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl;?>/styles/site.css" /> 
   </head>

   <body>
      <div id="content">
          
      </div>
   </body>
</html>