<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->escape($this->title); ?></title>
        <link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl;?>/styles/site.css" />
        <script src="<?php echo $this->baseUrl;?>/scripts/jquery-1.5.1.min.js" 
        type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl;?>/scripts/modernizr-1.7.min.js" 
        type="text/javascript"></script>
    </head>
    <body>
        <div class="page">
            <header>
                <div id="title">
                    <h1>System zgłaszania błędów</h1>
                </div>
                
                <!--
                <div id="logindisplay">
                    tutaj powinno być logowanie<br/>
                    <a href="<?php echo $this->baseUrl; ?>/user/loginform">Zaloguj się</a>
           
                </div>-->
                
                
                <nav>
                    <ul id="menu">
                        <li><a href="<?php echo $this->baseUrl; ?>">Gość</a></li>
                        <li><a href="<?php echo $this->baseUrl; ?>/user">Użytkownik</a></li>
                        <li><a href="<?php echo $this->baseUrl; ?>/admin">Administrator</a></li>
                        <?php 
                            if($this->escape($this->userrole)==""){?>
                                <li><a href="<?php echo $this->baseUrl; ?>/admin/tickets">Wszystkie tickety</a></li>
                            <?php }
                            else {?> <li><a href="<?php echo $this->baseUrl; ?>/admin/tickets">Wszystkie tickety</a></li> 
                                <?php }
                        ?>
                    </ul>
                </nav>
            </header>
            <section id="main">
