<form action="<?php echo $this->baseUrl ?>/user/<?php
      echo $this->action; ?>" method="post">
   <div>
      <label hidden for="author">Autor</label> 
      <input type="hidden" name="author" value="<?php
         echo $this->escape(trim($this->username));?>"/> 
   </div><br/>
    
   <div>
      <label for="cathegory">Kategoria</label>
      <input required="required" type="text" name="cathegory" placeholder="Naciśnij dwa razy" list="datalist"/>
      <datalist id="datalist">
          <option value="problem z komputerem w sali">
          <option value="awaria komputera pracownika">
          <option value="inne">
          <option value="awaria sieci">
      </datalist>
   </div><br/>
   
   <div>
      <label for="problem_describe">Opis problemu</label>
      <input required="required" rows="4" cols="8" type="text" name="problem_describe" value="<?php
         echo $this->escape($this->userticket->problem_describe);?>"/>
   </div><br/>
    
   <div>
      <label hidden for="send_data">Data wysłania</label>
      <input type="hidden" name="send_data" value="<?php
         echo date("Y-m-d");?>"/> 
   </div><br/>
    
   <div>
      <label hidden for="end_data">Data zakończenia</label>
      <input type="hidden" name="end_data" value="0"/> 
   </div><br/>
    
   <div>
      <label hidden for="status">Status</label>
      <input type="hidden" name="status" value="oczekujący"/> 
   </div> <br/>
    
   <div>
       <label hidden for="ip_number">Numer IP</label>
      <input type="hidden" name="ip_number" value="<?php
         echo $_SERVER['REMOTE_ADDR'];?>"/> 
   </div><br/>   
   
   <div>
      <label hidden for="admin1">Admin 1</label>
      <input type="hidden" name="admin1" value="-"/>
   </div><br/>  
   
   <div>
      <label hidden for="admin2">Admin 2</label>
      <input type="hidden" name="admin2" value="-"/>
   </div><br/>  
   
   <div>
       <label hidden for="admin3">Admin 3</label>
      <input type="hidden" name="admin3" value="-"/>
   </div><br/>
    
    
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->userticket->id; ?>" /> 
      <input type="submit" name="add" value="Dodaj" />
   </div>
</form>