<?php echo $this->render('header.phtml'); ?>  

<form method='post' action='<?=$this->escape($this->action);?>'>
  <table>
    <tr>
	  <td><?=$this->escape($this->username);?></td>
	  <td><input type='text' name='username'></td>
	</tr>
    <tr>
	  <td><?=$this->escape($this->password);?></td>
	  <td><input type='password' name='password'></td>
	</tr>	
  </table>
    <br/>
  <input type='submit' name='login' value='Zaloguj się'>
  </form>

<?php echo $this->render('footer.phtml'); ?>