<form action="<?php echo $this->baseUrl ?>/admin/<?php
      echo $this->action; ?>" method="post">
   <div>
      <label for="author">Autor</label>
      <input required="required" type="text" name="author" value="<?php
         echo $this->escape(trim($this->guestticket->author));?>"/>
   </div><br/>

   <div>
      <label for="cathegory">Kategoria</label>
      <input required="required" type="text" name="cathegory" placeholder="Naciśnij dwa razy" list="datalist" value="<?php
         echo $this->escape(trim($this->guestticket->cathegory));?>"/>
      <datalist id="datalist">
          <option value="problem z komputerem w sali">
          <option value="awaria komputera pracownika">
          <option value="inne">
          <option value="awaria sieci">
      </datalist>
   </div><br/>
   
   <div>
      <label for="problem_describe">Opis problemu</label>
      <input required="required" rows="4" cols="8" type="text" name="problem_describe" value="<?php
         echo $this->escape(trim($this->guestticket->problem_describe));?>"/>
   </div><br/>  
   
   <div>
       <label for="subject_name">Nazwa przedmiotu</label>
      <input type="text" name="subject_name"/>
   </div><br/>
    
   <div>
      <label for="send_data">Data wysłania</label>
      <input required="required" type="text" name="send_data" value="<?php
         echo $this->escape(trim($this->guestticket->send_data));?>"/>
   </div><br/>
   
   <div>
      <label for="end_data">Data zakończenia</label>
      <input required="required" type="text" name="end_data" value="<?php
         echo $this->escape(trim($this->guestticket->end_data));?>"/>
   </div><br/>
    
   <div>
      <label for="status">Status</label>
      <input required="required"  placeholder="Naciśnij dwa razy" list="datalist2" type="text" name="status" value="<?php
         echo $this->escape($this->guestticket->status);?>"/>
      <datalist id="datalist2">
          <option value="brak">
          <option value="przyjęto zgłoszenie">
          <option value="oczekujący">
          <option value="w trakcie realizacji">
          <option value="wysłany do serwisu">
          <option value="zakończony">
          <option value="anulowany">
      </datalist>
   </div><br/>
    
   <div>
      <label for="ip_number">Numer IP</label>
      <input required="required" type="text" name="ip_number" value="<?php
         echo $this->escape($this->guestticket->ip_number);?>"/>
   </div><br/>    
   
   <div>
      <label for="admin1">Admin 1</label>
      <input type="text" name="admin1" value="<?php
         echo $this->escape($this->guestticket->admin1);?>"/>
   </div><br/>  
   
   <div>
      <label for="admin2">Admin 2</label>
      <input type="text" name="admin2" value="<?php
         echo $this->escape($this->guestticket->admin2);?>"/>
   </div><br/>  
   
   <div>
      <label for="admin3">Admin 3</label>
      <input type="text" name="admin3" value="<?php
         echo $this->escape($this->guestticket->admin3);?>"/>
   </div><br/>
    
    
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->guestticket->id; ?>" /> 
      <input type="submit" name="edit" value="<?php
         echo $this->escape($this->buttonText); ?>" />
   </div>
</form>