<form action="<?php echo $this->baseUrl ?>/admin/<?php echo $this->action; ?>" method="post">
   <table>
        <tr>
            <td><label for="userid">Id użytkownika</label> </td>
            <td><?php echo $this->escape(trim($this->userticket->userid));?></td>
        </tr>
        
        <tr>
      <td><label for="author">Autor</label></td>
      <td><?php echo $this->escape(trim($this->userticket->author));?></td>
        </tr>
        
        <tr hidden>
      <td><label for="author_name">author_name</label></td>
      <td><input type="text" name="author_name" value="<?php echo $this->escape(trim($this->userticket->author));?>"/></td>
        </tr>
        
        <tr hidden>
      <td><label for="e_mail">e_mail</label></td>
      <td><input type="text" name="e_mail" value="<?php echo $this->escape(trim($this->userticket->e_mail));?>"/></td>
        </tr>
   
   <tr>
      <td><label for="cathegory">Kategoria</label></td>
      <td><input required="required" type="text" name="cathegory" placeholder="Naciśnij dwa razy" list="datalist" value="<?php
         echo $this->escape(trim($this->userticket->cathegory));?>"/>
      <datalist id="datalist">
          <option value="problem z komputerem w sali">
          <option value="awaria komputera pracownika">
          <option value="inne">
          <option value="awaria sieci">
      </datalist></td>
   </tr>
   
   <tr>
      <td><label for="problem_describe">Opis problemu</label></td>
      <td><input required="required" rows="4" cols="8" type="text" name="problem_describe" value="<?php
         echo $this->escape($this->userticket->problem_describe);?>"/></td>
   </tr>
   
   <tr>
       <td><label for="subject_name">Nazwa przedmiotu</label></td>
       <td><input type="text" name="subject_name" value="<?php
         echo $this->escape($this->userticket->subject_name);?>"/></td>
   </tr>
    
   <tr>
      <td><label for="send_data">Data wysłania</label></td>
      <td><input required="required" type="text" name="send_data" value="<?php
         echo $this->escape($this->userticket->send_data);?>"/></td>
   </tr>
    
   <tr>
      <td><label for="end_data">Data zakończenia</label></td>
      <td><input required="required" type="text" name="end_data" value="<?php
         echo $this->escape(trim($this->userticket->end_data));?>"/></td>
   </tr>
    
   <tr>
      <td><label for="status">Status</label></td>
      <td><input required="required"  placeholder="Naciśnij dwa razy" list="datalist2" type="text" name="status" value="<?php
         echo $this->escape($this->userticket->status);?>"/> 
      <datalist id="datalist2">
          <option value="brak">
          <option value="przyjęto zgłoszenie">
          <option value="oczekujący">
          <option value="w trakcie realizacji">
          <option value="wysłany do serwisu">
          <option value="zakończony">
          <option value="anulowany">
      </datalist></td>
   </tr>
    
   <tr hidden>
      <td><label for="oldstatus">oldStatus</label></td>
      <td><input type="text" name="oldstatus" value="<?php echo $this->escape($this->userticket->status);?>"/></td>
   </tr>
    
   <tr>
      <td><label for="ip_number">Numer IP</label></td>
      <td><input required="required" type="text" name="ip_number" value="<?php
         echo $_SERVER['REMOTE_ADDR'];?>"/></td>
   </tr>
    
   <tr>
      <td><label for="admin1">Admin 1</label></td>
      <td><input type="text" name="admin1" value="<?php
         echo $this->escape($this->userticket->admin1);?>"/></td>
   </tr>
    
   <tr>
      <td><label for="admin2">Admin 2</label></td>
      <td><input type="text" name="admin2" value="<?php
         echo $this->escape($this->userticket->admin2);?>"/></td>
   </tr>
    
   <tr>
      <td><label for="admin3">Admin 3</label></td>
      <td><input type="text" name="admin3" value="<?php
         echo $this->escape($this->userticket->admin3);?>"/></td>
   </tr>  
   
   <tr>
      <td><label for="choose">Czy poza otrzymaniem na e-maila wiadomości<br/> o zakończeniu ticketu,
          chcesz także otrzymywać<br/> informacje o zmianach statusu twojego zgłoszenia?<br/> Jeżeli tak to zaznacz
          kwadracik.</label></td>
      <td><input required="required" type="text" name="choose" placeholder="Naciśnij dwa razy"  list="chooselist" value="<?php
         echo $this->escape($this->userticket->choose);?>" />
            <datalist id="chooselist">
                <option value="Tak">
                <option value="Nie">
            </datalist></td>
   </tr> 
   </table><br/> 
    
    
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->userticket->id; ?>" /> 
      <input type="submit" name="edit" value="<?php
         echo $this->escape($this->buttonText); ?>" />
   </div>
</form>