<form action="<?php echo $this->baseUrl ?>/index/<?php
      echo $this->action; ?>" method="post">
   <div>
      <label for="author">Autor</label> 
      <input type="text" name="author" value="<?php
         echo $this->escape(trim($this->guestticket->author));?>"/>
   </div>
    
    create table 'userticket'
    ( id int(6) auto_increment;
    author varchar(50) not null;
    cathegory enum('problem z komputerem w sali','awaria komputera pracownika','inne','awaria sieci');
    send_data datetime;
    end_data datetime;
    status enum('przyjęto zgłoszenie','oczekujący','w trakcie realizacji','wysłany do serwisu','zakończony','anulowany');
    ip_number varchar(20);
    primary key(id));
    
    create table userticket
    (id int(6) auto_increment,
    author varchar(50) not null,
    cathegory enum('problem z komputerem w sali','awaria komputera pracownika','inne','awaria sieci'),
    problem_describe text null,
    send_data datetime,
    end_data datetime,
    status enum('brak','przyjęto zgłoszenie','oczekujący','w trakcie realizacji','wysłany do serwisu','zakończony','anulowany'),
    ip_number varchar(20),
    primary key(id));
    
create table guestticket
    (id int(6) auto_increment,
    author varchar(50) not null default 'guest',
    cathegory enum('problem z komputerem w sali','awaria komputera pracownika','inne','awaria sieci'),
    problem_describe text null,
    send_data datetime,
    end_data datetime,
    status enum('brak','przyjęto zgłoszenie','oczekujący','w trakcie realizacji','wysłany do serwisu','zakończony','anulowany'),
    ip_number varchar(20),
    primary key(id));
    
    
    INSERT INTO userticket
    (id, author, cathegory, send_data, end_data, status, ip_number) 
    VALUES 
    ('','Majk','problem z komputerem w sali','','','oczekujący',''),
('','Majk','problem z komputerem w sali','','','oczekujący',''),
('','Majk2','problem z komputerem w sali','','','oczekujący',''),
('','Majk3','problem z komputerem w sali','','','oczekujący',''),
('','Majk4','problem z komputerem w sali','','','oczekujący',''),
('','Majk5','problem z komputerem w sali','','','oczekujący','')
        

CREATE TABLE users (
  id int(11) NOT NULL auto_increment,
  username varchar(50) NOT NULL,
  password varchar(255) NOT NULL,
  e_mail varchar(50) NOT NULL,
  role enum('user','admin') NOT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY username (username)
);

INSERT INTO zend.users (id ,username ,password ,e_mail ,role)
VALUES ('','Seik',MD5('admin'),'seikishin@gmail.com','admin'),
('','Majk',MD5('majk'),'majkmajk22@gmail.com','user');
   
    
ALTER TABLE guestticket ADD admin1 varchar(30) null;

   <div>
      <label for="cathegory">Kategoria</label>
      <input type="text" name="cathegory" value="<?php
         echo $this->escape($this->guestticket->cathegory);?>"/>
   </div>
    
   <div>
      <label for="send_data">Data wysłania</label>
      <input type="text" name="send_data" value="<?php
         echo $this->escape($this->guestticket->send_data);?>"/>
   </div>
    
   <div>
      <label for="end_data">Data zakończenia</label>
      <input type="text" name="end_data" value="<?php
         echo $this->escape($this->guestticket->end_data);?>"/>
   </div>
    
   <div>
      <label for="status">Status</label>
      <input type="text" name="status" value="<?php
         echo $this->escape($this->guestticket->status);?>"/>
   </div> 
    
   <div>
      <label for="ip_number">Numer IP</label>
      <input type="text" name="ip_number" value="<?php
         echo $this->escape($this->guestticket->ip_number);?>"/>
   </div>     
    
    
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->guestticket->id; ?>" /> 
      <input type="submit" name="add" value="<?php
         echo $this->escape($this->buttonText); ?>" />
   </div>
</form>











<form action="<?php echo $this->baseUrl ?>/index/<?php echo $this->action; ?>" method="post">
    <table>
        <tr hidden>
            <!--<td><label for="author">Autor</label> </td>-->
            <td><input type="hidden" name="author" value="Gość"/></td>
        </tr>
   
   <tr>
      <td><label for="cathegory">Kategoria</label></td>
      <td><input required="required" type="text" name="cathegory" placeholder="Naciśnij dwa razy" list="datalist"/>
      <datalist id="datalist">
          <option value="problem z komputerem w sali">
          <option value="awaria komputera pracownika">
          <option value="inne">
          <option value="awaria sieci">
      </datalist></td>
   <tr>
   
   <div>
      <label for="problem_describe">Opis problemu</label>
      <input required="required" rows="4" cols="8" type="text" name="problem_describe" value="<?php
         echo $this->escape($this->problem_describe);?>"/>
   </div><br/>
   
   <div>
       <label for="subject_name">Nazwa przedmiotu</label>
      <input type="text" name="subject_name" value="-"/>
   </div><br/>
    
   <div>
      <!--<label for="send_data">Data wysłania</label>-->
      <input type="hidden" name="send_data" value="<?php
         echo date("Y-m-d");?>"/>
   </div>
    
   <div>
      <!--<label for="end_data">Data zakończenia</label>-->
      <input type="hidden" name="end_data" value="0"/>
   </div>
    
   <div>
      <!--<label for="status">Status</label>-->
      <input type="hidden" name="status" value="oczekujący"/>
   </div>
    
   <div>
      <!--<label for="ip_number">Numer IP</label>-->
      <input type="hidden" name="ip_number" value="<?php
         echo $_SERVER['REMOTE_ADDR'];?>"/>
   </div><br/>     
   
   <div>
      <label hidden for="admin1">Admin 1</label>
      <input type="hidden" name="admin1" value="-"/>
   </div>  
   
   <div>
      <label hidden for="admin2">Admin 2</label>
      <input type="hidden" name="admin2" value="-"/>
   </div> 
   
   <div>
       <label hidden for="admin3">Admin 3</label>
      <input type="hidden" name="admin3" value="-"/>
   </div>
    </table>
    
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->guestticket->id; ?>" /> 
      <input type="submit" name="add" value="Dodaj" />
   </div>
</form>